language: node_js
node_js:
  - v9.11.2
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registrations_tests

before_script:
  - psql -c 'create database registrations_tests' -U postgres
  - psql -U postgres -d registrations_tests -a -f table.sql
